version: '3.8'


services:
  db:
    image: postgres:16.1
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: examensw02
    volumes:
      - ./postgres2:/var/lib/postgresql/data